apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-app-secret
spec:
  provider: aws
  parameters: 
    objects: |
      - objectName: "my-app-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: dbusername
          - path: password
            objectAlias: dbpassword
  secretObjects:                
    - secretName: k8s-secret
      type: Opaque
      data:
        - objectName: dbusername
          key: username
        - objectName: dbpassword
          key: password